config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: true, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(strong_restaurant_params) # Create restaurant with strong params - the params that I have allowed
    @restaurant.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.htm.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>

<% end %>

app/views/restaurants/index.html.erb
<h1>🍤All restaurants 🌯</h1>
<% @restaurants.each do |restaurant| %>
  <p><strong> <%= link_to restaurant.name, restaurant_path(restaurant) %></strong> <%= restaurant.phone_number %>
    - <%= restaurant.address %></p>
<% end %>


<%= link_to "Add a new restaurant", new_restaurant_path  %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit %>

<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>

<%= link_to 'Back to all restaurants', restaurants_path  %>

app/views/reviews/new.html.erb
<h1>Add a new review</h1>


<%= simple_form_for @review do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>

<% end %>